### PR TITLE
Fix Enhanced Backspace on rules that backpace normal keypresses

### LINKED ISSUE #28: Enhanced Backspace doesn't work correctly with certain rules
Rules with backspaces don't work correctly with enhanced backspace:
```
[rule] uldn't✪ ⇒ uld've
[FAIL] Output buffer size after backspaces: 2

[rule] i'm✪ ⇒ i'll
[FAIL] Output buffer size after backspaces: 1

[rule] i'll☆ ⇒ i've
[FAIL] Output buffer size after backspaces: 1

[rule] you're☆ ⇒ you'll
[FAIL] Output buffer size after backspaces: 1

[rule] you'll✪ ⇒ you've
[FAIL] Output buffer size after backspaces: 1

[rule] they're☆ ⇒ they'll
[FAIL] Output buffer size after backspaces: 1

[rule] they'll✪ ⇒ they've
[FAIL] Output buffer size after backspaces: 1

[rule] judge✪ ⇒ judgment
[FAIL] Output buffer size after backspaces: 3
```

### PR DESCRIPTION
**Pull request by Ikcelaks**
`resend_output` failed to tap the backspaces if the first key that needed to be resent was from a normal keypress.

Example:
```
judge* -> judgment
```
Tapping backspace after `judge*` should backspace 3 times (plus the first automatic backspace) and then output `e`. Since the `*` action deleted `e`, which is a normal keypress, the 3 backspaces were not sent. So, the output was `judgmene`.

This PR fixes that.

### CODE REVIEW

File: sequence_transform.c [hunk 1]
```diff
@@ -297,7 +297,7 @@ void st_find_missed_rule(void)
     st_trie_rule_t result;
     result.sequence = sequence_str;
     result.transform = transform_str;
-    const int new_len = st_trie_get_rule(&trie, &key_buffer, search_len_start, &result);    
+    const int new_len = st_trie_get_rule(&trie, &key_buffer, search_len_start, &result);
```
Comment (Ikcelaks) [inline sequence_transform.c:300]: Removing this white space was not an intentional change. I wonder what is causing my editor to do this light weight linting.

**Review by QRiary — APPROVED** [review]

**Review by kamih — APPROVED** [review]
Looks good! All rules now backspace correctly when testing manually, and with automatic tester.
